#!/bin/bash

# git-credential-gpg
#
# INSTRUCTIONS
# ------------
#
# Set this script as credential helper in your .gitconfig:
#   [credential]
#       helper = /path/to/git-credential-gpg
#
# Make an encrypted file storing your password or OAuth token:
#   $ echo "password=YOUR_OAUTH_TOKEN_HERE" | gpg -a -e -r YOUR_KEYID_HERE --output CREDFILE.asc
#
# Add the file to the credfile array below:
#   credfile['USERNAME@HOST']=CREDFILE.asc

[ "$1" != "get" ] && exit 1

declare -A credfile

creddir=~/git-credential-gpg
credfile['myname@gmail.com@smtp.gmail.com:587']=gmail.asc
credfile['myname@github.com']=github.asc

while true; do
    read input
    case $input in
    host=*)     host=${input#*=} ;;
    username=*) username=${input#*=} ;;
    '')         gpg -dqq $creddir/${credfile["$username@$host"]}
                exit 0 ;;
    esac
done
